# Generated by Django 5.0 on 2023-12-29 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('Time', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='reserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carNo', models.CharField(max_length=20)),
                ('phnNo', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='booking',
            name='reserverId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park_basic.reserver'),
        ),
    ]
