# Generated by Django 5.0 on 2023-12-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('park_basic', '0004_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='CustomUser',
        ),
    ]
