# Generated by Django 5.0 on 2023-12-29 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_basic', '0006_reserver_userid_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slotId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='park_basic.bookingslot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserver',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
