# Generated by Django 5.0 on 2023-12-31 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_basic', '0007_booking_slotid_alter_reserver_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserver',
            name='carNo',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid car registration number.', regex='^([a-zA-Z]{1,3}|([0-9]{1,3}))-[0-9]{4}$')]),
        ),
    ]
